### ISSUE TITLE
Build zone doesn't auto close on first time use

### ISSUE THREAD

**Issue by MustacheMan2** [yuwui/Uchu#240] opened 2021-06-21 15:49 UTC

**Comment by teccheck** [comment] 2021-09-14 14:25
Do you mean the build zone for rockets or cars? When should it auto close?

**Comment by enteryournamehere** [comment] 2021-09-14 16:36
https://user-images.githubusercontent.com/11255568/133297534-85eef468-5b3e-4508-bee1-50fc60195b82.mp4

When you click the blue Done button, you should exit the build mode, but currently this doesn't always work: in this video I still need to press Exit afterwards to actually leave the build zone. Note that this doesn't consistently happen: I just tried it on a local server and on an external one, and on the local one I _did_ automatically exit after pressing Done while on the external one I did not. It's possible that there's a race condition somewhere.

**Comment by teccheck** [comment] 2021-09-14 17:23
I see. Gonna look into it

**Comment by enteryournamehere** [comment] 2021-09-14 19:29
Forgot to add this earlier: it applies to car building too (although that's a bit broken in other ways), and actually I believe also to pet taming: see [this video](https://youtu.be/5BPo5o04-74?t=45), it's the same state that you're in when building a rocket/car. But when in pet taming mode, there's no exit button, so you're just stuck after submitting the name.

**Comment by teccheck** [comment] 2021-09-14 19:34
Do you know if this happened on Micks server? It would be cool to have logs of this happening. I haven't had this problem while I was testing my code (and I tested a lot)

**Comment by enteryournamehere** [comment] 2021-09-14 19:38
Yes it did. I can reproduce and get you some logs later today or tomorrow. Do you want to add any additional logging besides what's currently being logged on the `dev` branch (at the Debug level)?

**Comment by teccheck** [comment] 2021-09-14 19:40
Maybe you could log what functions are called in `ModularBuilderComponent`

**Comment by teccheck** [comment] 2021-09-14 19:50
I guess I already fixed this... I can reproduce this on `dev` but not on `enhancement/modular-building`

**Comment by enteryournamehere** [comment] 2021-09-15 07:37
Not sure how, but it does indeed appear to be fixed on your branch, I can't reproduce it there either :+1:

**Comment by teccheck** [comment] 2021-09-15 09:32
I guess the problem was that if you dropped a rocket onto the builder it wouldn't move the parts into `TempModels` so the `FinishBuild` method wouldn't find them. I think I fixed that in the commit `Implement StartArrangingWithModelMessage`

**Closed as completed** 2021-10-28 15:09 UTC
Labels: type: bug, affects: gameplay
