### ISSUE TITLE
Error when loading standard scripts in release

### ISSUE THREAD

**Issue by teccheck** [yuwui/Uchu#308] opened 2021-10-28 19:15 UTC
When I join my server on my raspberrypi I get this error when loading venture explorer. I built the latest Uchu with the `linux-arm64` framework using a modded `publish.py`.

```
[Info ] [Z1000] 192.168.178.25:42720's validating client for world!                                                                        
[Info ] [Z1000] Parsing: maps/01_live_maps/space_ship/nd_space_ship.luz                                                                    
[Info ] [Z1000] Parsing: nd_space_ship.lvl                                                                                                 
[Info ] [Z1000] Parsed: 1000                                                                                                               
[Info ] [Z1000] Starting 1000                                                                                                              
[Info ] [Z1000] Checksum: 0x20B8087C                                                                                                       
[Info ] [Z1000] Collecting objects for 1000                                                                                                
[Info ] [Z1000] Loading native scripts...                                                                                                  
[Error] [Z1000] System.IO.DirectoryNotFoundException: Could not find a part of the path                                                    
                '/home/ubuntu/uchu/lib/lib/Uchu.StandardScripts.dll'.
                at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
                at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
                at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
                at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize,
                FileOptions options)
                at System.IO.File.ReadAllBytes(String path)
                at Uchu.World.Scripting.Native.NativeScriptPack.ReadAssembly()
                at Uchu.World.Scripting.ScriptManager.LoadNativeScripts()
[Info ] [Z1000] Loading managed scripts...                                                                                                 
[Info ] [Z1000] Loading 145 objects for 1000 
```

It tries to load `Uchu.StandardScripts.dll` from `/home/ubuntu/uchu/lib/lib/`, but the file is in `/home/ubuntu/uchu/lib/`

**Comment by TheNexusAvenger** [comment] 2022-01-13 21:08
Assigning this to myself because I am interested in this.
Running it on a Raspberry Pi is an interesting use case. Is it worth adding ARM/ARM64 releases?

**Edit**: Confirmed it is an issue with the Linux release in general. It isn't an issue on Windows though.

**Comment by TheNexusAvenger** [comment] 2022-01-22 22:41
Looked into this on a fresh install of Manjaro Linux. This issue only happens if you also have `dotnet` configured. I have determined how this should be fixed yet, but I will be looking at it soon.

**Closed as completed** 2022-02-10 16:29 UTC
